## Differents Arrays

In [2]:
import numpy as np

In [6]:
# Array of Zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
# More complex array of Zeros by using a tuple
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [36]:
# Array of Ones
np.ones((4, 2, 2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [38]:
# Create an array with any other Numbers
np.full((2, 3), 100, dtype='float16')

array([[100., 100., 100.],
       [100., 100., 100.]], dtype=float16)

In [44]:
# Array with a given shape with any number
a = np.array([[1, 2, 3, 4, 5],[2, 4, 6, 8, 10]])

np.full_like(a, 4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [61]:
# Random decimal numbers
np.random.rand(3, 2)


array([[0.82009966, 0.99477713],
       [0.3774214 , 0.05731781],
       [0.4678094 , 0.74766613]])

In [63]:
np.random.random_sample(a.shape)

array([[0.65394124, 0.62746088, 0.49067782, 0.91273643, 0.23087158],
       [0.27418431, 0.11517707, 0.13520158, 0.05674534, 0.33131731]])

In [67]:
# Ramdom Integers (range, shape)
np.random.randint(10, size=(2, 2))

array([[8, 4],
       [0, 6]])

In [73]:
# Identity Matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [90]:
# Repeat an array elements
arr = np.array([[3, 2, 3]])
# (array, times, axis)
arr2 = np.repeat(arr, 4, axis=0)
arr2

array([[3, 2, 3],
       [3, 2, 3],
       [3, 2, 3],
       [3, 2, 3]])

# CHALLENGE
Create a Matrix with the following shape using arrays only

   1, 1, 1, 1, 1 \
   1, 0, 0, 0, 1 \
   1, 0, 9, 0, 1 \
   1, 0, 0, 0, 1 \
   1, 1, 1, 1, 1 

In [34]:
ones = np.ones((5, 5))
zeros = np.zeros((3, 3))
nine = np.array(9)

zeros[1, 1] = nine
ones[1:4,1:4] = zeros
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Copying
#### We must be carefully when copying numpy arrays

In [43]:
# Creating an array
a = np.array([1, 2, 3])
# We 'copy' the array a
b = a

# Changing a value in the array copied
b[0] = 100
# b = [100, 2, 3] 
# a = [100, 2, 3] Also!!!
print(f'b array equals: {b} \nAnd a array equals: {a} too!')



b array equals: [100   2   3] 
And a array equals: [100   2   3] too!


In [52]:
# Using copy() function
bcopy = a.copy()
# So we change an elenment
bcopy[0] = 99

print(f"New array using copy {bcopy}")
print(f"First array {a}")
# And 'a' array does not change anymore :)

New array using copy [99  2  3]
First array [100   2   3]
