In [2]:
import numpy as np
print(np.__version__)

1.21.5


## CREATING ARRAYS

In [44]:
a = np.array([1, 2, 3, 4, 5], dtype='int8')
a

array([1, 2, 3, 4, 5], dtype=int8)

In [40]:
b = np.array([[1.1,2.1, 3.3], [2.2, 4.4, 6.8,]], dtype='float16')
b

array([[1.1, 2.1, 3.3],
       [2.2, 4.4, 6.8]], dtype=float16)

In [7]:
# Dimension
b.ndim

2

In [24]:
# Shape
b.shape

(2, 3)

In [23]:
# Type
b.dtype

dtype('float64')

In [45]:
# Size
a.nbytes

5

## ACCESSING AND CHAGING ELEMENTS

In [4]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [8]:
# GET an specific element [row, column]
a[1, -2]

13

In [11]:
# GET an specific ROW [row, all:column]
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
# GET an specific COLUMN [all:rows, column]
a[:,2]

array([ 3, 10])

In [19]:
# [ROW, StartIndex: EndIndex: Stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [21]:
# Change an element
a[1, 5] = 22
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 22, 14]])

In [23]:
# Change a column
a[:, 2] = [10, 11]
a

array([[ 1,  2, 10,  4,  5,  6,  7],
       [ 8,  9, 11, 11, 12, 22, 14]])

In [29]:
b = np.array([[[1, 2],[3, 4]], [[5, 6],[7, 8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [34]:
# Get an element from a 3d array
b[:, 1, :]

array([[3, 4],
       [7, 8]])

In [38]:
# Replace in 3D arrays
b[:, 1, :] = [[0,0],[0,0]]
b

array([[[1, 2],
        [0, 0]],

       [[5, 6],
        [0, 0]]])